-- Run this once in the Supabase SQL editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.antimony_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id text not null,
  persona text not null,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists antimony_messages_user_session_idx
  on public.antimony_messages(user_id, session_id, created_at);

create table if not exists public.antimony_agents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  agent_key text not null,
  profile jsonb not null default '{}'::jsonb,
  visibility text not null default 'private' check (visibility in ('private', 'shared')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, agent_key)
);

create table if not exists public.antimony_tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null,
  done boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.antimony_messages enable row level security;
alter table public.antimony_agents enable row level security;
alter table public.antimony_tasks enable row level security;

-- The browser must use only the anon/publishable key. Anonymous visitors get no
-- table access; signed-in users are still constrained by the RLS policies below.
revoke all on table public.profiles from anon;
revoke all on table public.antimony_messages from anon;
revoke all on table public.antimony_agents from anon;
revoke all on table public.antimony_tasks from anon;
grant select, insert, update, delete on table public.profiles to authenticated;
grant select, insert, update, delete on table public.antimony_messages to authenticated;
grant select, insert, update, delete on table public.antimony_agents to authenticated;
grant select, insert, update, delete on table public.antimony_tasks to authenticated;
grant usage, select on sequence public.antimony_messages_id_seq to authenticated;
grant usage, select on sequence public.antimony_agents_id_seq to authenticated;
grant usage, select on sequence public.antimony_tasks_id_seq to authenticated;

drop policy if exists "profiles own rows" on public.profiles;
create policy "profiles own rows" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "messages own rows" on public.antimony_messages;
create policy "messages own rows" on public.antimony_messages for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "agents read own or shared" on public.antimony_agents;
create policy "agents read own or shared" on public.antimony_agents for select
  using (auth.uid() is not null and (auth.uid() = user_id or visibility = 'shared'));
drop policy if exists "agents write own rows" on public.antimony_agents;
create policy "agents write own rows" on public.antimony_agents for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "tasks own rows" on public.antimony_tasks;
create policy "tasks own rows" on public.antimony_tasks for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id, display_name)
  values (
    new.id,
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'username'), ''),
      nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''),
      nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
      case when new.phone is not null then 'User ' || right(new.phone, 4) else 'Antimony User' end
    )
  )
  on conflict (id) do update set
    display_name = coalesce(nullif(public.profiles.display_name, ''), excluded.display_name),
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- This function is for the auth trigger only, not a browser RPC.
revoke execute on function public.handle_new_user() from public, anon, authenticated;
